--- BUSINESS PROJECT CASE 3: CUSTOMER ANALYTICS & SEGMENTATION

------ SECTION A — Customer Exploration

--- 1. Display all customers from the customers table.
SELECT * FROM customers;

--- 2. Display customers from a specific city.
SELECT *
FROM customers
WHERE city = 'Lagos';


--- 3. Display Distinct city from customers.
SELECT DISTINCT city 
FROM customers;

--- 4. Find the total number of customers.
SELECT COUNT(customer_id) AS "Total Customers"
FROM customers;

--- 5. Count customers by gender.
SELECT 	gender,
		COUNT(*) AS "Total Customers"
FROM customers
GROUP BY gender
ORDER BY "Total Customers" DESC;


---- 6. Count customers by customer segment.
SELECT  customer_segment,
		COUNT(*) AS "Total Customers"
FROM customers
GROUP BY customer_segment
ORDER BY "Total Customers" DESC;

---- 7. Display customers sorted by registration date from oldest to newest.
SELECT * FROM customers
ORDER BY registration_date ASC;

---- 8. Display the 10 most recently registered customers.
SELECT * FROM customers
ORDER BY registration_date DESC
LIMIT 10;


---- SECTION B — Customer Orders Analysis

---- 9.Display customer names together with their orders.
SELECT  c.first_name,
		c.last_name,
		o.order_date,
		o.order_status,
		o.sales_channel,
		o.total_amount,
		o.discount_amount,
		o.net_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id;

---- 10. Find the total number of orders placed by each customer.
SELECT  c.first_name,
		c.last_name,
		COUNT(o.order_id) AS "Total Order"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.first_name,
		 c.last_name
ORDER BY "Total Order" DESC;

---- 11. Find the total amount spent by each customer.
SELECT  c.last_name,
		c.first_name,
		SUM(o.net_amount) AS "Total Amount Spent"
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.last_name,
		 c.first_name
ORDER BY "Total Amount Spent" DESC;

---- 12. Find the average order amount for each customer.
SELECT  c.last_name,
		c.first_name,
		AVG(o.net_amount) AS "Average Amount Spent"
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.last_name,
		 c.first_name
ORDER BY "Average Amount Spent" DESC;


--- 13. Find customers who placed more than 5 orders.
SELECT  c.first_name,
		c.last_name,
		COUNT(o.order_id) AS "Total Order"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.first_name,
		 c.last_name
HAVING COUNT(o.order_id) > 5
ORDER BY "Total Order" DESC;

---- 14. Find the top 10 customers by total spending.
SELECT  c.last_name,
		c.first_name,
		SUM(o.net_amount) AS "Total Amount Spent"
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.last_name,
		 c.first_name
ORDER BY "Total Amount Spent" DESC
LIMIT 10;

---- 15. Find customers who have completed orders.
SELECT 	c.first_name,
		c.last_name,
		o.order_status
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id 
WHERE o.order_status = 'Completed';

---- SECTION C — Customer Spending Analysis

----- 16. Calculate total revenue generated by each customer segment.
SELECT 	c.customer_segment,
		SUM(o.net_amount) AS "Revenue"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_segment
ORDER BY "Revenue" DESC;

---- 17. Calculate average order amount by customer segment.
SELECT 	c.customer_segment,
		AVG(o.net_amount) AS "Average Revenue"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_segment
ORDER BY "Average Revenue" DESC;

---- 18. Find the customer segment with the highest revenue.
SELECT 	c.customer_segment,
		SUM(o.net_amount) AS "Revenue"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_segment
ORDER BY "Revenue" DESC
LIMIT 1;

---- 19. Find the number of customers in each segment.
SELECT 	customer_segment,
		COUNT(customer_id) AS "Total Customers"
FROM customers
GROUP BY customer_segment
ORDER BY "Total Customers" DESC;

---- 20. Find the highest spending customer.
SELECT  c.last_name,
		c.first_name,
		SUM(o.net_amount) AS "Total Amount Spent"
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.last_name,
		 c.first_name
ORDER BY "Total Amount Spent" DESC
LIMIT 1;


---- SECTION D — Customer Product Behaviour

---- 21. Display customers and the products they purchased.
SELECT	o.order_id,
		c.first_name,
		c.last_name,
		p.product_name,
		oi.line_total
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
JOIN orders o
ON oi.order_id = o.order_id
JOIN customers c
ON c.customer_id = o.customer_id
ORDER BY o.order_id ASC;

---- 22. Find the number of different products purchased by each customer.
SELECT 	c.first_name,
		c.last_name,
		COUNT(DISTINCT oi.product_id) AS "Total Order"
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.first_name,
		 c.last_name
ORDER BY "Total Order" DESC;


----- 23. Find the total quantity purchased by each customer.
SELECT 	c.first_name,
		c.last_name,
		SUM(oi.quantity) AS "Total Quantity"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id 
GROUP BY 	c.first_name,
			c.last_name
ORDER BY "Total Quantity" DESC;

---- 24. Find the most purchased product.
SELECT 	p.product_name,
		SUM(oi.quantity) AS "Total"
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY "Total" DESC
LIMIT 1;

----- 25. Find revenue generated from each product category.
SELECT 	ca.category_name,
		SUM(oi.line_total * oi.quantity) AS "Revenue"
FROM categories ca
JOIN products p
ON ca.category_id = p.category_id
JOIN order_items oi
on p.product_id = oi.product_id
GROUP BY ca.category_name
ORDER BY "Revenue" DESC;
	

---- SECTION E — Customer Business Report

---- 26. Create a report showing:- Customer name, Total orders, and Total spending
SELECT 	c.first_name,
		c.last_name,
		COUNT(o.order_id) AS "Total Orders",
		SUM(o.net_amount) AS "Total Spending"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY 	c.first_name,
			c.last_name
ORDER BY "Total Orders" DESC;


---- 27. Find the average order amount.
SELECT AVG(net_amount) AS "Average Order Amount"
FROM orders;

---- 28. Find the highest order value for each customer.
SELECT	c.first_name,
		c.last_name,
		MAX(o.net_amount) AS "Highest Order"
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY 	c.first_name,
			c.last_name
ORDER BY "Highest Order" DESC;


---- 29. Find the stores where customers made purchases.
SELECT DISTINCT	c.first_name,
				c.last_name,
				s.store_name
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN stores s
ON s.store_id = o.store_id
GROUP BY	c.last_name,
			c.first_name,
			s.store_name;

----- 30. Create a customer summary showing: - Total customers, Total orders, and Total revenue
SELECT	 COUNT(DISTINCT c.customer_id) AS "Total Customer",
		 COUNT(o.order_id) AS "Total Order",
		 SUM(o.net_amount) AS "Total Revenue"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id;

---- SECTION F — CASE WHEN Customer Classification

--- 31. Classify customers based on spending: 500000 and above = High Value Customer, 200000 to below 500000 = Medium Value, and Customer Below 200000 = Low Value Customer
SELECT 	c.last_name,
		c.first_name,
		SUM(o.net_amount) AS "Total Spending",
	CASE
		WHEN SUM(o.net_amount) >= 50000 THEN 'High Valued Customer'
		WHEN SUM(o.net_amount)  >= 20000 THEN 'Medium Valued Customer'
		ELSE 'Low Valued Customer'
		END AS "Customer Level"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY    c.last_name,
			c.first_name;

---- 32. Classify customers based on order frequency:  More than 10 orders = Frequent Buyer, 5 to 10 orders = Regular Buyer, and Below 5 orders = Occasional Buyer
SELECT	c.last_name,
		c.first_name,
		COUNT(o.order_id) AS "Total Order",
	CASE
		WHEN COUNT(o.order_id) >= 10 THEN 'Frequent Buyer'
		WHEN COUNT(o.order_id) >= 5 THEN 'Regular Buyer'
		ELSE 'Occassional Buyer'
		END AS "Buyer Type"
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY 	c.last_name,
			c.first_name;


--- 33. Create spending categories: 500000 and above = Premium, 200000 to below 500000 = Standard, and Below 200000 = Basic
SELECT 	c.last_name,
		c.first_name,
		SUM(o.net_amount) AS "Total Spending",
	CASE
		WHEN SUM(o.net_amount) >= 500000 THEN 'Premium'
		WHEN SUM(o.net_amount)  >= 200000 THEN 'Standard'
		ELSE 'Basic'
		END AS "Customer Level"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY    c.last_name,
			c.first_name;



---- 34. Classify orders: Above 100000 = Large Order, 50000 to 100000 = Medium Order, and Below 50000 = Small Order
SELECT 	c.last_name,
		c.first_name,
		o.net_amount AS "Total Spending",
	CASE
		WHEN o.net_amount >= 100000 THEN 'Large Order'
		WHEN o.net_amount  >= 50000 THEN 'Medium Order'
		ELSE 'Small Order'
		END AS "Customer Level"
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY    c.last_name,
			c.first_name,
			o.net_amount;

---- 35. Create customer loyalty labels: More than 10 orders = Loyal Customer and Others = Occasional Customer
SELECT	c.last_name,
		c.first_name,
		COUNT(o.order_id) AS "Total Order",
	CASE
		WHEN COUNT(o.order_id) >= 10 THEN 'Loyal Cuatomer'
		ELSE 'Ocassional Customer'
		END AS "Buyer Type"
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY 	c.last_name,
			c.first_name;
























